apiVersion: v1
kind: Service
metadata:
  name: api-mapa-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: api-mapa  # Asegúrate de que coincida con las etiquetas de tu Deployment
